# Generated by Django 6.0.7 on 2026-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='leaves',
            field=models.JSONField(default=list),
        ),
    ]
