# Generated by Django 6.0.7 on 2026-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorprofile_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='leaves',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
