# Generated by Django 6.0.8 on 2026-08-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_id_alter_doctorprofile_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
