# Generated by Django 6.0.8 on 2026-08-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
