# Generated by Django 6.0.8 on 2026-08-05 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prescribedmedicine_medicationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('systolic', models.IntegerField(blank=True, help_text='Systolic BP', null=True)),
                ('diastolic', models.IntegerField(blank=True, help_text='Diastolic BP', null=True)),
                ('blood_sugar', models.IntegerField(blank=True, help_text='Blood Sugar in mg/dL', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart Rate in bpm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='core.patientprofile')),
            ],
        ),
    ]
